# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082cc9d603282497e55ab7f20f22a721888c7576045d6ab16f55156f67f667f12f57ab991054a71f6445f118f2ac0c6efdd4ea927ce25fa6dbe96eaecddb9de6

test:
  secret_key_base: da26058b4f2b4d96e3fb26187824d5faa2d3e76204053038d1e3752aa4ed35767673536a6ef2ed81b4607223e893b2301dea49de878d61ff96893344769cb955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
